# docker-compose.dev.yml (Development)
version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - ENV_FILE=${ENV_FILE:-'.env.development'}
      - API_HOST=${API_HOST:-http://localhost}
      - API_PORT=${API_PORT:-8000}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - MODEL_CACHE_DIR=${MODEL_CACHE_DIR:-models}
      - HF_AUTH_TOKEN=${HF_AUTH_TOKEN}
    volumes:
      - ./back:/app
      - ./back/models:/app/models
      - ./back/processed_audio:/app/processed_audio
      - ./back/temp_uploads:/app/temp_uploads
    ports:
      - "${API_PORT:-8000}:8000"
    command: uvicorn api:app --reload --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
        - VITE_WS_BASE_URL=${VITE_WS_BASE_URL:-ws://localhost:8000}
    restart: unless-stopped
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-3000}:5173"
    depends_on:
      - backend